In [1]:
import numpy as np
print(np.__version__)
np.random.randn()

1.21.5


1.111102928010747

In [5]:
x1 = np.random.randint(10, size=6)
print(x1)

[5 0 3 3 7 9]


In [16]:
np.random.seed(0)  # seed for reproducibility
x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array
print("x1\n",x1)
print("x2\n",x2)
print("x3\n",x3)

x1
 [5 0 3 3 7 9]
x2
 [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
x3
 [[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [22]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
x[4:7]

array([4, 5, 6])